### ISSUE TITLE
about training cost

### ISSUE THREAD

**Issue by PointsCoder** [nickgkan/3d_diffuser_actor#15]
Hi,

Thanks for your great work!

I am trying to train your model on CALVIN and found that the training time is very long. In your default setting it seems to train for 600000 iterations and will take 200 GPU hours on my side. Can I ask what is the training setting (how many GPU cards, batch size on a single GPU card, training iterations) for your best CALVIN models?

**Comment by PointsCoder** [comment]
I found some useful explanations from prior issues #9 #5 , but there is still a question I want to ask:
You said that you used batch size 1080 with 6 GPU cards, but it seems that 40GB cards can only accommodate batch size 30 in each GPU, so I am wondering your exact setting for training CALVIN?

**Comment by twke18** [comment]
Hi,

The effective batch size in our experiments is in fact `num_gpus * num_episodes_per_gpu * length_per_episode`.  You can see [this line](https://github.com/nickgkan/3d_diffuser_actor/blob/e576b69daec958c9706865b662b79bb068170220/datasets/dataset_calvin.py#L124) for chunking every episode.  If the length of the episode is smaller than the specified one, we will use the whole episode.  In our experiments, we use [6 gpus](https://github.com/nickgkan/3d_diffuser_actor/blob/e576b69daec958c9706865b662b79bb068170220/scripts/train_trajectory_calvin.sh#L14), [30 episodes per gpu](https://github.com/nickgkan/3d_diffuser_actor/blob/e576b69daec958c9706865b662b79bb068170220/scripts/train_trajectory_calvin.sh#L12), and [a maximum episode length of 30](https://github.com/nickgkan/3d_diffuser_actor/blob/e576b69daec958c9706865b662b79bb068170220/scripts/train_trajectory_calvin.sh#L40C7-L40C25).  That is to say, our maximal batch size would be 5400, not 1080.  We didn't notice this mistake until now! Sorry for the confusion.

On CALVIN, I believe you don't need to train the full 600,000 iterations.  We just trained for 65,000 iterations in our experiments.  Also, we didn't ablate the effect of different batch size, since we spent most our effort on experiments in RLBench.

**Comment by PointsCoder** [comment]
Thank you! That addressed my concerns.

**Comment by chenfengxu714** [comment]
Hi,

I notice that in your training log, your training takes one day. I use 6 A6000 GPUS with your script config for 60K iteration, yet it takes ~6 days. May I know any modification can accelerate it? I think there should be some misalignments between yours and ours. 

Best regards

**Comment by twke18** [comment]
Hi,

IO is indeed the bottleneck of our code base.  We hosted the data on a SSD disk.  If not using SSD, it would take a lot of time for training the model.  Also, the number of threads matters.  Our CPU is a AMD EPYC 7502 32-Core Processor.

**Comment by chenfengxu714** [comment]
Thanks for your reply! yeah, I tweak a little bit of these settings and now it can be trained in one day!
