### ISSUE TITLE
language  use 

### ISSUE THREAD

**Issue by Cherryjingyao** [nickgkan/3d_diffuser_actor#17]
I run the code and I want to change the plan work.
But when I debug, i can't find the batch["lang"] in the data.I'm wandering how u use lang embedding
when I check the code in hulc.py:
 if "lang" in self.modality_scope:
                latent_goal = self.language_goal(dataset_batch["lang"])
self.modality_scope is setted to be "vim"
so what does the latent language representation refer to ?

**Comment by Cherryjingyao** [comment]
add more to the previous comment .I found the part of the batch data  "vim" ,and part of them is 'lang" .why is this setting?
where is the data processing code? if I want to use another lang embedding of another language encoder ,how can i change the code?
Thanks for your answering

**Comment by nickgkan** [comment]
For anyone coming to this issue in the future: the field for the language instruction is "instr". For the data preprocessing code, see our readme https://github.com/nickgkan/3d_diffuser_actor?tab=readme-ov-file#optional-encode-language-instructions.

That said, there's no hulc.py in our codebase, so probably this issue was mistakenly addressed to us? In any case, our codebase is different from HULC's.
