### ISSUE TITLE
about real world data？

### ISSUE THREAD

**Issue by lunalulu** [nickgkan/3d_diffuser_actor#2]
thanks for your great work!!

also i have some questions below:
1、 I want to use the 3d Diffuser actor on an actual robotic arm, but I'm not clear enough on how to collect real data. Can you provide some scripts or instructions?

2、Can the real world dataset be open sourced?

3、Does predicting the frequency of keyposes determine whether an outward movement planner is needed? For example, if the intervals between predicted keyposes are small and the relative changes are small, is there no need for this additional planner? and How to decide if one need a planner？

4、what does the following sentence mean? what's the corresponding trajectory?
![image](https://github.com/nickgkan/3d_diffuser_actor/assets/40664601/21ca3d73-a66d-48e0-806d-917173e60a01)

Once again I would like to express my gratitude and look forward to your reply!

**Comment by twke18** [comment]
Thanks for your interest!  Setting up real-world experiments in fact requires quite some efforts!  In our lab, we use Franka Emika robot to collect and present real-world manipulation demos.

1. See [this repo](https://github.com/zhouxian/franka) for setting up Franka robot.  We recorded only the keyposes for our real-world experiments.  For example, for "put duck in plate", the keyposes are the following: gripper on top of duck, gripper has grasped duck, gripper on top of the plate, gripper lowers down and releases. See our paper (appendix) for more details.
2. We can provide our collected real-world demos.  However, you still need to set up the real-world robot to test/present manipulation in the real world.  For reference, our robot/scene setup can be seen in our paper and the videos on our website. Since real-robot setups are probably different per lab, our real-world training data would possibly be useful for reference only.
3. Yes, you're right.  If the relative change between neighboring keyposes is small, you don't need a motion planner.  Conceptually, let `K1` and `K2` be two neighboring keyposes, and we need to find a path to reach `K2` from `K1`.  If these two poses are close,  you can reach the target pose via a straight line, otherwise, you need to deploy a motion planner or learn a policy to predict the intermediate path.
4. Following 3., our 3D Diffuser Actor can predict both `K2` and the intermediate path.  We predict `K2` only for RLBench and use the RRT planner to connect keyposes. We predict both `K2` and the trajectory up to `K2` for CALVIN.

**Comment by lunalulu** [comment]
@twke18 Thank you for your detailed reply！
The current situation is that I probably don’t have the same model of robotic arm as the one in the paper. In this case, I should be able to refer to the paper for actual data collection, right?

**Comment by nickgkan** [comment]
Hi @lunalulu, although we do not name the semantics of each keypose, we do provide the number of keyposes per task in our appendix. Based on the "put duck in plate" example, you could infer the logic behind real-world data collection. If you have doubts about a specific task or need some more advice, don't hesitate to ask us.
Good luck! Let us know how 3D Diffuser Actor performs on your setup!
