### ISSUE TITLE
Request for Checkpoint with Trajectory

### ISSUE THREAD

**Issue by LemonWade** [nickgkan/3d_diffuser_actor#23]
First of all, thank you for your efforts in developing and sharing this valuable project. It has been very helpful.

I am currently noticed that the available checkpoint seems to be for keypose. I am particularly interested in trajectory.

Would it be possible for you to share a checkpoint about trajectory? 

Thank you in advance for considering my request. I look forward to your positive response.

**Comment by twke18** [comment]
Hi,

Thanks for your interest!  We only train the trajectory model on CALVIN, and here is the [link](https://huggingface.co/katefgroup/3d_diffuser_actor/blob/main/diffuser_actor_calvin.pth) of the model weights.

To test the model, you can try [this script](https://github.com/nickgkan/3d_diffuser_actor/blob/master/scripts/test_trajectory_calvin.sh)

To train your own model, you can run [this script](https://github.com/nickgkan/3d_diffuser_actor/blob/master/scripts/train_trajectory_calvin.sh)

To train 3D Diffuser Actor with trajectory on RLBench, you can run [this script](https://github.com/nickgkan/3d_diffuser_actor/blob/master/scripts/train_trajectory_peract.sh).  Since sampling-based motion planners (e.g. RRT) work well on the 18 PerAct tasks, we found the performance is similar with/without predicting trajectory.

**Comment by LemonWade** [comment]
Thank you very much for your response
