### ISSUE TITLE
Training on a single task

### ISSUE THREAD

**Issue by pawanw17** [nickgkan/3d_diffuser_actor#31]
Hi, Thanks for the great work!

I am trying to train 3d_diffuser_actor on a single task "turn tap", the graphs (attached below) show that the model is learning well and converging but when using the [inference script](https://github.com/nickgkan/3d_diffuser_actor/blob/master/online_evaluation_rlbench/eval_act3d_peract.sh). I am not seeing the desired results, can you please help identify what could be going wrong?

In the [training script](https://github.com/nickgkan/3d_diffuser_actor/blob/master/scripts/train_keypose_peract.sh) I changed "ngpus" to 1 and passed only "turn_tap" to "tasks"

![image](https://github.com/nickgkan/3d_diffuser_actor/assets/40732709/587d4a4f-ddbe-4e4d-8485-b8cad8fa0374)
![image](https://github.com/nickgkan/3d_diffuser_actor/assets/40732709/04e2d8df-f93e-4eb6-877a-0c334e94ab55)

I am training on a single A4000 GPU

**Comment by twke18** [comment]
Hi,

It is very likely to a problem of normalization.  You can set [this argument](https://github.com/nickgkan/3d_diffuser_actor/blob/2ab63276a29464a4b6b223ea5472df6100984db8/online_evaluation_rlbench/eval_act3d_peract.sh#L12) to 1, so that the location bound is selected to be the same as training.  If you only specify one task in the training script, [this function](https://github.com/nickgkan/3d_diffuser_actor/blob/2ab63276a29464a4b6b223ea5472df6100984db8/utils/common_utils.py#L23-L37) will select the bound of that task, instead of aggregating among all tasks.

**Comment by pawanw17** [comment]
Hi,

That was it! changing the parameter single_task_gripper_loc_bounds to 1 worked. Thank you so much! I wish I had asked this sooner...
