### ISSUE TITLE
Inquiry about RLBench .dat file format and considerations for real-world experiment

### ISSUE THREAD

**Issue by ggggfff1** [nickgkan/3d_diffuser_actor#54]
Hi

Could you kindly provide information on the format of the **.dat** files(for example: close_jar+10/ep0.dat)   in the RLBench dataset? Additionally, if I were to conduct experiments using real-world data, what would be the essential considerations to keep in mind? Would I need to collect and preprocess data in a format similar to the simulation data used in RLBench for training purposes?

**Comment by nickgkan** [comment]
Hi,
The content of .dat files is directly loaded through our dataset classes. You can find a reference on its format here https://github.com/nickgkan/3d_diffuser_actor/blob/master/datasets/dataset_engine.py#L133-L141.

For real-world experiments, if you want to use our data loaders, then you can try to package the data into the same format. Otherwise, writing your own data loader is also an option.

Some considerations: make sure the point cloud looks normal and visualize the gripper annotations on the point cloud. Also, make sure to compute the gripper location bounds correctly. These are the most common bugs.

Good luck!
