### ISSUE TITLE
Instruction preprocesing

### ISSUE THREAD

**Issue by windboy6** [nickgkan/3d_diffuser_actor#56]
Hi,

I want to know why the original text encoder of CLIP is not used, which has a length of 77, but 53?
Why does the instruction encoder use VIT, since the image encoder uses resnet50？

![image](https://github.com/user-attachments/assets/e2c3b0e5-640f-4d58-9fd9-104368e7e90b)

![image](https://github.com/user-attachments/assets/d2d0b992-a405-46bd-901b-023bf654be9d)

**Comment by nickgkan** [comment]
Hi,

1. It is the original text encoder of CLIP, we just ask it to return 53 instead of 77 tokens since all our sentences are shorter, so we don't want to waste computations in the attention layers.
2. The performance is the same no matter which CLIP text encoder you use, at least on RLBench that we tested this.

**Comment by xiaohao9999** [comment]
Ok. Thanks for your timely reply！

**Comment by windboy6** [comment]
Hi, 

Thanks for your timely reply! I have a few more questions.

1. I noticed that when generating data, collision detection is not required by default. What is the reason for this?
2. I noticed that you didn't use low_dim_state. Shouldn't this information be very important in robot operation?

**Comment by nickgkan** [comment]
Hi,

1. For the tasks we train/test on, collision detection is not needed.
2. We don't need/use any state information in our model, other than where the end-effector currently is. We want a perception-based policy.

**Comment by windboy6** [comment]
Hi,

Thank you for your detailed explanation!
