### ISSUE TITLE
Don't need collision detection?

### ISSUE THREAD

**Issue by xiaohao9999** [nickgkan/3d_diffuser_actor#76]
Hi,

I have some questions about the loss in the paper, previous work has required a loss for collision detection, why not here?

![image](https://github.com/user-attachments/assets/3337efa5-6ba0-481a-8c06-8a23ced0ae37)

**Comment by nickgkan** [comment]
We find that for these tasks we do not need collision detection, therefore we don't predict a relevant flag. In addition, collision detection has been used by some past works on RLBench, specifically by predicting a binary flag on whether to avoid collisions or not. Its behavior is specific to the underlying simulator and there's not really a ground-truth value for it. Thus, we opted to discard this value completely.

**Comment by xiaohao9999** [comment]
Indeed, and there's no way to set up collision damage in the real world, is there?

**Comment by nickgkan** [comment]
Since this is handled by the low-level planner, it depends on what planner you're going to use. If your planner accepts any arguments, you can in theory predict them with your model, but to get annotations for that, you would need to manually decide the target values, which defeats the purpose of learning and is also hard to design.

**Comment by xiaohao9999** [comment]
Thanks for your clear answer!
